### ISSUE TITLE
Something wrong with npm-sass? 

### ISSUE THREAD

**Issue by phifa** [t3easy/docker-surf#3]
I had used the `t3easy/surf:gulp-node8.9` successfully in the past, and wanted to deploy again, but now I am getting this: 

```
> WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
> > node-sass@4.7.2 install /root/.surf/workspace/test/TYPO3 CMS/build/project.com/node_modules/node-sass > node scripts/install.js
> module.js:538     throw err;     ^  Error: Cannot find module '/root/.surf/workspace/test/TYPO3 CMS/build/project.com/node_modules/node-sass/scripts/install.js'     at Function.Module._resolveFilename (module.js:536:15)     at Function.Module._load (module.js:466:25)     at Function.Module.runMain (module.js:676:10)     at startup (bootstrap_node.js:187:16)     at bootstrap_node.js:608:3
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm
> ERR!
> node-sass@4.7.2 install: `node scripts/install.js` npm ERR! Exit status 1 npm ERR!  npm ERR! Failed at the node-sass@4.7.2 install script. npm
```

Any idea what might be going on?

**Comment by t3easy** [comment]
First please see: https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#cannot-find-module-rootinstalljs
BTW.: I had no problems with node-sass 4.9.2 today w/o 
Maybe it's also a problem with the locked fsevents for darwin.

But I could not reproduce it.

To test the this you could run the docker image local:
`docker run --rm -it t3easy/surf:gulp-node8.9 /bin/sh`
create the package.json and lock and run `npm install`.

**Comment by Geddo** [comment]
Got this one for today:
```
> > phantomjs-prebuilt@2.1.14 install /root/.surf/workspace/master/TYPO3 CMS/build/xxxxx/node_modules/phantomjs-prebuilt > node install.js
> module.js:538     throw err;     ^  Error: Cannot find module '/root/.surf/workspace/master/TYPO3 CMS/build/xxxxx/node_modules/phantomjs-prebuilt/install.js'     at Function.Module._resolveFilename (module.js:536:15)     at Function.Module._load (module.js:466:25)     at Function.Module.runMain (module.js:676:10)     at startup (bootstrap_node.js:187:16)     at bootstrap_node.js:608:3
> npm WARN optional
> SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js` npm ERR! Exit status 1
```

**Comment by t3easy** [comment]
@phifa @Geddo Could you upload a package.json and lock.

**Comment by phifa** [comment]
Yes, no problem. I work with foundation. Pretty simple setup from here: 
https://foundation.zurb.com/sites/docs/installation.html#install-with-foundation-cli 

The files as txt: 
[package-lock.json.txt](https://github.com/t3easy/docker-surf/files/2245831/package-lock.json.txt)
[package.json.txt](https://github.com/t3easy/docker-surf/files/2245832/package.json.txt)

**Comment by t3easy** [comment]
I couldn't reproduce the problem...
```
~/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld # npm install
npm WARN notice [SECURITY] tunnel-agent has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=tunnel-agent&version=0.4.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] tough-cookie has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=tough-cookie&version=2.2.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.8 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> node-sass@4.7.2 install /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux_musl-x64-57_binding.node
Download complete .] - :
Binary saved to /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Caching binary to /root/.npm/node-sass/4.7.2/linux_musl-x64-57_binding.node

> phantomjs-prebuilt@2.1.16 install /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [==============================----------] 75%
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1533051912982/phantomjs-2.1.1-linux-x86_64 -> /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> gifsicle@3.0.4 postinstall /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ spawn /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" --bindir="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" && make install
Command failed: autoreconf -ivf
/bin/sh: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

> jpegtran-bin@3.2.0 postinstall /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ spawn /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
Command failed: ./configure --disable-shared --prefix="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor"
configure: error: in `/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/3f30cc1c-85fd-4111-8035-cf3b6485b722':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

> optipng-bin@3.1.4 postinstall /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ⚠ spawn /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng ENOENT
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
Command failed: ./configure --with-system-zlib --prefix="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor"

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

> node-sass@4.7.2 postinstall /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/node-sass
> node scripts/build.js

Binary found at /root/.surf/workspace/master/TYPO3 CMS/build/very-log-domain-for-project-x.tld/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Testing binary
Binary is fine
added 4875 packages in 111.849s
```

Could you test it by yourself?
Maybe a problem with the npm cache?
Where did the deployment run? GitLab CI?

**Comment by t3easy** [comment]
Any new intel @Geddo @phifa?

**Comment by phifa** [comment]
@t3easy I am still trying to work on your suggestion 

> To test the this you could run the docker image local:

As I am on Windows and not experienced with docker, I am not sure how to do this. I will let you know.

**Comment by phifa** [comment]
@t3easy I was now able to spin up docker and test it directly in your image. I got the same output as you, so looking good. I am using Bitbucket Pipelines to deploy. I just tried again to deploy using Pipelines, and got the same error. Weird. Any ideas? In my post-install-cmd I am running `npm install && npm run-script build`.

**Comment by t3easy** [comment]
Maybe it's a problem of the npm cache or of packages under node_modules that are in vcs. Could you try to flush the npm cache before install? And check if anything under node_packages is in git.

**Comment by phifa** [comment]
no, it doesnt work. error persists. strange. @Geddo were you able to fix it?

**Comment by t3easy** [comment]
I close this for now.
